# Generated by Django 5.2.8 on 2025-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('programa', models.CharField(max_length=100)),
            ],
        ),
    ]
